# Generated by Django 3.1.7 on 2021-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0002_auto_20210625_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='digital_product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
