# Generated by Django 3.1.7 on 2021-06-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0003_auto_20210626_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='debit_card',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
