# Generated by Django 3.1.7 on 2021-06-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0004_auto_20210626_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='content_creator.Creative'),
        ),
    ]
