# Generated by Django 3.1.7 on 2021-06-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0008_auto_20210626_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='Thumbs_Upped',
            field=models.ManyToManyField(blank=True, related_name='likes', to='content_creator.Creative'),
        ),
    ]
