# Generated by Django 3.1.7 on 2021-06-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0009_auto_20210626_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Thumbs_Upped',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='content_creator.Creative'),
        ),
        migrations.AlterField(
            model_name='review',
            name='anon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_creator.creative'),
        ),
    ]
