# Generated by Django 3.1.7 on 2021-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0012_auto_20210628_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creative',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
