# Generated by Django 3.1.7 on 2021-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0014_auto_20210629_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creative',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
