# Generated by Django 3.1.7 on 2021-06-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0015_auto_20210630_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
