# Generated by Django 3.1.7 on 2021-07-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0019_auto_20210630_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_snippet',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_upload',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
